version: "3.9"

services:
  java_app:
    container_name: java_app
    image: usuarios
    build: .
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    command: bash -c "mvn clean package && java -jar target/*.jar"
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
